### ISSUE TITLE
Bug - Classic Era Multiple Death Entries

### ISSUE THREAD

**Issue by Jorvanus** [aaronma37/Deathlog#11] opened 2023-08-26 00:26 UTC
Occasionally there is two posts for deaths. 

![image](https://github.com/aaronma37/Deathlog/assets/89010934/47afa7e2-34c6-4bb7-9594-3ccac601f2db)

**Comment by aaronma37** [comment] 2023-08-26 16:05
Ah thanks for the heads up.  I'm not sure what the root cause is, but we can do a little bit better with caching recent deaths so they don't show at least

**Comment by aaronma37** [comment] 2023-09-05 17:43
Fix merged

**Closed by aaronma37** 2023-09-05 17:43 UTC
